name: Go Library CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.go-version.outputs.go_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go version
        id: go-version
        run: |
          version=$(grep '^go ' go.mod | awk '{print $2}')
          echo "go_version=$version" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.go_version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.go-version.outputs.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.go-version.outputs.go_version }}-

      - name: Download Go modules
        run: make download-deps

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go_version }}
      - name: Lint Go Code
        run: make lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go_version }}
      - name: Test Go Code
        run: make test
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: reports/coverage

  compile:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go_version }}
      - name: Compile Go Code
        run: make compile